%% Generated by the Erlang ASN.1 compiler. Version: 5.0.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module MMS.

-ifndef(_MMS_HRL_).
-define(_MMS_HRL_, true).

-record('UnconfirmedPDU', {
  unconfirmedService
}).

-record('ConfirmedRequestPdu', {
  invokeID,
  confirmedServiceRequest
}).

-record('ConfirmedResponsePdu', {
  invokeID,
  confirmedServiceResponse
}).

-record('ObjectName_domainspecific', {
  domainId,
  itemId
}).

-record('InitiateRequestPdu', {
  localDetailCalling = asn1_NOVALUE,
  proposedMaxServOutstandingCalling,
  proposedMaxServOutstandingCalled,
  proposedDataStructureNestingLevel = asn1_NOVALUE,
  mmsInitRequestDetail
}).

-record('InitRequestDetail', {
  proposedVersionNumber,
  proposedParameterCBB,
  servicesSupportedCalling
}).

-record('InitiateResponsePdu', {
  localDetailCalled = asn1_NOVALUE,
  negotiatedMaxServOutstandingCalling,
  negotiatedMaxServOutstandingCalled,
  negotiatedDataStructureNestingLevel = asn1_NOVALUE,
  mmsInitResponseDetail
}).

-record('InitResponseDetail', {
  negotiatedVersionNumber,
  negotiatedParameterCBB,
  servicesSupportedCalled
}).

-record('ServiceError', {
  errorClass,
  additionalCode = asn1_NOVALUE,
  additionalDescription = asn1_NOVALUE
}).

-record('GetNameListRequest', {
  objectClass,
  objectScope,
  continueAfter = asn1_NOVALUE
}).

-record('GetNameListResponse', {
  listOfIdentifier,
  moreFollows = asn1_DEFAULT
}).

-record('TypeSpecification_array', {
  packed = asn1_DEFAULT,
  numberOfElements,
  elementType
}).

-record('TypeSpecification_structure', {
  packed = asn1_DEFAULT,
  components
}).

-record('TypeSpecification_floatingpoint', {
  formatwidth,
  exponentwidth
}).

-record('StructComponent', {
  componentName = asn1_NOVALUE,
  componentType
}).

-record('AlternateAccess_SEQOF_selectAlternateAccess', {
  accessSelection,
  alternateAccess
}).

-record('AlternateAccess_SEQOF_selectAlternateAccess_accessSelection_indexRange', {
  lowIndex,
  numberOfElements
}).

-record('AlternateAccess_SEQOF_named', {
  componentName,
  accesst
}).

-record('AlternateAccessSelection_selectAlternateAccess', {
  component,
  index,
  indexRange,
  allElements,
  alternateAccess
}).

-record('AlternateAccessSelection_selectAlternateAccess_indexRange', {
  lowIndex,
  numberOfElements
}).

-record('IndexRangeSeq', {
  lowIndex,
  numberOfElements
}).

-record('ReadRequest', {
  specificationWithResult = asn1_DEFAULT,
  variableAccessSpecification
}).

-record('ReadResponse', {
  variableAccessSpecification = asn1_NOVALUE,
  listOfAccessResult
}).

-record('WriteRequest', {
  variableAccessSpecification,
  listOfData
}).

-record('GetVariableAccessAttributesResponse', {
  mmsDeletable,
  typeSpecification
}).

-record('InformationReport', {
  variableAccessSpecification,
  listOfAccessResult
}).

-record('DefineNamedVariableListRequest', {
  variableListName,
  listOfVariable
}).

-record('GetNamedVariableListAttributesResponse', {
  mmsDeletable,
  listOfVariable
}).

-record('DeleteNamedVariableListRequest', {
  scopeOfDelete = asn1_DEFAULT,
  listOfVariableListName = asn1_NOVALUE,
  domainName = asn1_NOVALUE
}).

-record('DeleteNamedVariableListResponse', {
  numberMatched,
  numberDeleted
}).

-record('VariableDef', {
  variableSpecification,
  alternateAccess = asn1_NOVALUE
}).

-record('ScatteredAccessDescription_SEQOF', {
  componentName = asn1_NOVALUE,
  variableSpecification,
  alternateAccess = asn1_NOVALUE
}).

-endif. %% _MMS_HRL_
