%% Generated by the Erlang ASN.1 compiler. Version: 5.0.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module ACSE.

-ifndef(_ACSE_HRL_).
-define(_ACSE_HRL_, true).

-record('AARQapdu', {
  protocolversion = asn1_NOVALUE,
  applicationcontextname,
  calledAPtitle = asn1_NOVALUE,
  calledAEqualifier = asn1_NOVALUE,
  calledAPinvocationidentifier = asn1_NOVALUE,
  calledAEinvocationidentifier = asn1_NOVALUE,
  callingAPtitle = asn1_NOVALUE,
  callingAEqualifier = asn1_NOVALUE,
  callingAPinvocationidentifier = asn1_NOVALUE,
  callingAEinvocationidentifier = asn1_NOVALUE,
  senderacserequirements = asn1_NOVALUE,
  mechanismname = asn1_NOVALUE,
  callingauthenticationvalue = asn1_NOVALUE,
  applicationcontextnamelist = asn1_NOVALUE,
  implementationinformation = asn1_NOVALUE,
  userinformation = asn1_NOVALUE
}).

-record('AAREapdu', {
  protocolversion = asn1_NOVALUE,
  applicationcontextname,
  result,
  resultsourcediagnostic,
  respondingAPtitle = asn1_NOVALUE,
  respondingAEqualifier = asn1_NOVALUE,
  respondingAPinvocationidentifier = asn1_NOVALUE,
  respondingAEinvocationidentifier = asn1_NOVALUE,
  applicationcontextnamelist = asn1_NOVALUE,
  implementationinformation = asn1_NOVALUE,
  userinformation = asn1_NOVALUE
}).

-record('RLRQapdu', {
  reason = asn1_NOVALUE,
  userinformation = asn1_NOVALUE
}).

-record('RLREapdu', {
  reason = asn1_NOVALUE,
  userinformation = asn1_NOVALUE
}).

-record('Myexternal', {
  directreference = asn1_NOVALUE,
  indirectreference = asn1_NOVALUE,
  encoding
}).

-endif. %% _ACSE_HRL_
