%% Generated by the Erlang ASN.1 compiler. Version: 5.0.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module Presentation.

-ifndef(_PRESENTATION_HRL_).
-define(_PRESENTATION_HRL_, true).

-record('CPtype', {
  modeselector,
  normalmodeparameters = asn1_NOVALUE
}).

-record('CPtype_normalmodeparameters', {
  protocolversion = asn1_DEFAULT,
  callingpresentationselector = asn1_NOVALUE,
  calledpresentationselector = asn1_NOVALUE,
  presentationcontextdefinitionlist = asn1_NOVALUE,
  defaultcontextname = asn1_NOVALUE,
  presentationrequirements = asn1_NOVALUE,
  usersessionrequirements = asn1_NOVALUE,
  userdata = asn1_NOVALUE
}).

-record('CPAPPDU', {
  modeselector,
  normalmodeparameters = asn1_NOVALUE
}).

-record('CPAPPDU_normalmodeparameters', {
  protocolversion = asn1_DEFAULT,
  respondingpresentationselector = asn1_NOVALUE,
  presentationcontextdefinitionresultlist = asn1_NOVALUE,
  presentationrequirements = asn1_NOVALUE,
  usersessionrequirements = asn1_NOVALUE,
  userdata = asn1_NOVALUE
}).

-record('Resultlist_SEQOF', {
  result,
  transfersyntaxname = asn1_NOVALUE,
  providerreason = asn1_NOVALUE
}).

-record('Modeselector', {
  modevalue
}).

-record('PDVlist', {
  transfersyntaxname = asn1_NOVALUE,
  presentationcontextidentifier,
  presentationdatavalues
}).

-record('Contextlist_SEQOF', {
  presentationcontextidentifier,
  abstractsyntaxname,
  transfersyntaxnamelist
}).

-record('Defaultcontextname', {
  abstractsyntaxname,
  transfersyntaxname
}).

-endif. %% _PRESENTATION_HRL_
